<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Paket;
use Illuminate\Support\Facades\DB;

class PaketSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pakets')->insert([
            [
                'nama_paket' => 'Catering 1',
                'kategori_id' => 2,
                'deskripsi' => 'Ayam goreng, nasi, sayur, sambal, kerupuk, pisang, air mineral(220 ml)',
                'modal' => 20000.00,
                'harga_jual' => 25000.00,
                'gambar' => 'catering.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Catering 2',
                'kategori_id' => 2,
                'deskripsi' => 'Cincang Lembu, nasi, sayur, kerupuk, jeruk, air mineral(220 ml)',
                'modal' => 27000.00,
                'harga_jual' => 32000.00,
                'gambar' => 'catering2.webp',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Catering 3',
                'kategori_id' => 2,
                'deskripsi' => 'Ikan mas arsik, nasi, sayur, kerupuk, pisang, air mineral(220 ml)',
                'modal' => 22000.00,
                'harga_jual' => 27000.00,
                'gambar' => 'catering3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Salon 1',
                'kategori_id' => 3,
                'deskripsi' => 'Pakaian adat karo komplit dan salon kedua mempelai',
                'modal' => 700000.00,
                'harga_jual' => 1000000.00,
                'gambar' => 'adat.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Salon 2',
                'kategori_id' => 3,
                'deskripsi' => 'Salon kedua mempelai dan salon orang tua( 2 pasang )',
                'modal' => 800000.00,
                'harga_jual' => 1500000.00,
                'gambar' => 'pemberkatan.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Gedung Utama',
                'kategori_id' => 1,
                'deskripsi' => 'Gedung utama (kapasitas 1000), tikar, kebersihan',
                'modal' => 500000.00,
                'harga_jual' => 5000000.00,
                'gambar' => 'gedung.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Gedung Resepsi',
                'kategori_id' => 1,
                'deskripsi' => 'Gedung resepsi (kapasitas 300), kursi, kebersihan',
                'modal' => 150000,
                'harga_jual' => 3000000.00,
                'gambar' => 'gedung2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'MUA 1',
                'kategori_id' => 3,
                'deskripsi' => 'Make-Up khusus pengantin wanita (pemberkatan atau adat), menggunakan produk make-up yang premium.',
                'modal' => 1000000.00,
                'harga_jual' => 1500000.00,
                'gambar' => 'mua.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'MUA 2',
                'kategori_id' => 3,
                'deskripsi' => 'Make-Up kedua mempelai (pemberkatan atau adat), menggunakan produk make-up yang premium.',
                'modal' => 1600000.00,
                'harga_jual' => 2000000.00,
                'gambar' => 'mua2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Pakaian Adat Karo',
                'kategori_id' => 7,
                'deskripsi' => 'Pakaian adat karo komplit kedua mempelai',
                'modal' => 700000.00,
                'harga_jual' => 1000000.00,
                'gambar' => 'adat.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Musik Biasa',
                'kategori_id' => 5,
                'deskripsi' => 'Sound system dan Keyboard.',
                'modal' => 600000.00,
                'harga_jual' => 750000.00,
                'gambar' => 'sound.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Musik Komplit',
                'kategori_id' => 5,
                'deskripsi' => 'Sound system, Keyboard, Alat Musik Karo Komplit',
                'modal' => 1500000.00,
                'harga_jual' => 1750000.00,
                'gambar' => 'musik.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Papan Bunga Jumbo',
                'kategori_id' => 4,
                'deskripsi' => 'Satu papan bunga jumbo',
                'modal' => 300000.00,
                'harga_jual' => 400000.00,
                'gambar' => 'papan.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Dekorasi Bunga Plastik',
                'kategori_id' => 4,
                'deskripsi' => 'Dekorasi bunga plastik untuk gereja',
                'modal' => 800000.00,
                'harga_jual' => 1000000.00,
                'gambar' => 'plastik.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Dekorasi Bunga Hidup',
                'kategori_id' => 4,
                'deskripsi' => '- Bunga gereja dan bunga pelaminan',
                'modal' => 3000000.00,
                'harga_jual' => 4000000.00,
                'gambar' => 'hidup.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Mobil Pengantin',
                'kategori_id' => 7,
                'deskripsi' => 'Mobil pengantin dengan dekorasi bunga.',
                'modal' => 500000.00,
                'harga_jual' => 700000.00,
                'gambar' => 'mobil.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Shooting foto',
                'kategori_id' => 6,
                'deskripsi' => 'Dokumentasi foto dan video ( 3 jam, 3 roll).',
                'modal' => 800000.00,
                'harga_jual' => 1350000.00,
                'gambar' => 'dok.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Photo Booth',
                'kategori_id' => 4,
                'deskripsi' => 'Photo booth untuk acara.',
                'modal' => 900000.00,
                'harga_jual' => 1500000.00,
                'gambar' => 'booth.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}