<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Paket;
use Illuminate\Support\Facades\DB;

class PaketSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pakets')->insert([
            [
                'nama_paket' => 'Cat1',
                'kategori_id' => 1,
                'deskripsi' => 'Ayam, sayur, sambal, kerupuk, nasi, minum.',
                'modal' => 15000.00,
                'harga_jual' => 18000.00,
                'gambar' => 'catering.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Sal1',
                'kategori_id' => 2,
                'deskripsi' => 'Pakaian adat karo komplit + Salon.',
                'modal' => 700000.00,
                'harga_jual' => 1000000.00,
                'gambar' => 'adat.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Sal2',
                'kategori_id' => 2,
                'deskripsi' => 'Salon kedua mempelai + Salon orang tua( 2 pasang )',
                'modal' => 800000.00,
                'harga_jual' => 1500000.00,
                'gambar' => 'pemberkatan.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Paket 800',
                'kategori_id' => 6,
                'deskripsi' => '- Makan siang untuk 800 orang (daging, ayam, ikan).\n - Salon 6 pasang.\n - Dekorasi.\n - Sound system, Keyboard, dan Pemusik.\n - Foto dan shooting video.\n - Pelaminan.\n - Luah adat.',
                'modal' => 17500000.00,
                'harga_jual' => 21000000.00,
                'gambar' => 'gedung.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Paket 1000',
                'kategori_id' => 6,
                'deskripsi' => '- Makan siang untuk 1000 orang (daging, ayam, ikan).\n - Salon 6 pasang.\n - Dekorasi.\n - Sound system, Keyboard, dan Pemusik.\n - Foto dan shooting video.\n - Pelaminan.\n - Luah adat.',
                'modal' => 20000000.00,
                'harga_jual' => 24000000.00,
                'gambar' => 'gedung.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Paket 1300',
                'kategori_id' => 6,
                'deskripsi' => '- Makan siang untuk 1300 orang (daging, ayam, ikan).\n - Salon 6 pasang.\n - Dekorasi.\n - Sound system, Keyboard, dan Pemusik.\n - Foto dan shooting video.\n - Pelaminan.\n - Luah adat.',
                'modal' => 23000000.00,
                'harga_jual' => 29000000.00,
                'gambar' => 'gedung.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Paket 1500',
                'kategori_id' => 6,
                'deskripsi' => '- Makan siang untuk 1500 orang (daging, ayam, ikan).\n - Salon 6 pasang.\n - Dekorasi.\n - Sound system, Keyboard, dan Pemusik.\n - Foto dan shooting video.\n - Pelaminan.\n - Luah adat.',
                'modal' => 27000000.00,
                'harga_jual' => 31500000.00,
                'gambar' => 'gedung.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Gedung Jambur',
                'kategori_id' => 6,
                'deskripsi' => 'Sewa gedung jambur untuk acara(air, listrik, tikar, kebersihan).',
                'modal' => 3000000.00,
                'harga_jual' => 5000000.00,
                'gambar' => 'gedung.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Gedung Prasmanan (50)',
                'kategori_id' => 6,
                'deskripsi' => '- Gedung Prasmanan untuk 50 orang.\n - Kursi balut 50 pcs.\n - Meja panjang 2 pcs.\n - Meja penerima tamu 1 pcs.',
                'modal' => 500000.00,
                'harga_jual' => 800000.00,
                'gambar' => 'gedung2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Gedung Prasmanan (100)',
                'kategori_id' => 6,
                'deskripsi' => '- Gedung Prasmanan untuk 100 orang.\n - Kursi balut 50 pcs.\n - Meja panjang 2 pcs.\n - Meja penerima tamu 1 pcs.',
                'modal' => 700000.00,
                'harga_jual' => 1000000.00,
                'gambar' => 'gedung2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Gedung Resepsi',
                'kategori_id' => 6,
                'deskripsi' => 'Gedung untuk resepsi.',
                'modal' => 1000000.00,
                'harga_jual' => 2000000.00,
                'gambar' => 'gedung2.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Catering Sarapan',
                'kategori_id' => 1,
                'deskripsi' => 'Pilihan :\n - Nasi + manuk gundur.\n - Nasi + jipang + cincang lembu.\n - Nasi + kentang buncis + cincang lembu.\n - Nasi + terong + timun + manuk.',
                'modal' => 10000.00,
                'harga_jual' => 18000.00,
                'gambar' => 'catering.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Catering Maba belo selambar',
                'kategori_id' => 1,
                'deskripsi' => 'Catering MBS Jambur',
                'modal' => 10000.00,
                'harga_jual' => 18000.00,
                'gambar' => 'catering.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Make Up Artist(MUA)',
                'kategori_id' => 2,
                'deskripsi' => 'Make-Up khusus pengantin wanita selama 2 hari(pasu-pasu & adat) dan menggunakan produk make-up yang premium.',
                'modal' => 700000.00,
                'harga_jual' => 1000000.00,
                'gambar' => 'mua.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Salon Ose-ose',
                'kategori_id' => 2,
                'deskripsi' => 'Pakaian adat karo komplit.',
                'modal' => 700000.00,
                'harga_jual' => 1000000.00,
                'gambar' => 'adat.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Sound System',
                'kategori_id' => 4,
                'deskripsi' => 'Sound system dan Keyboard.',
                'modal' => 500000.00,
                'harga_jual' => 1000000.00,
                'gambar' => 'sound.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Papan Bunga Jumbo',
                'kategori_id' => 3,
                'deskripsi' => 'Satu papan bunga jumbo.',
                'modal' => 100000.00,
                'harga_jual' => 200000.00,
                'gambar' => 'papan.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Dekorasi Bunga Plastik',
                'kategori_id' => 3,
                'deskripsi' => 'Dekorasi bunga plastik untuk Gereja.',
                'modal' => 800000.00,
                'harga_jual' => 1000000.00,
                'gambar' => 'plastik.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Dekorasi Bunga Hidup',
                'kategori_id' => 3,
                'deskripsi' => '- Bunga gereja.\n - Bunga pelaminan.\n - Kombinasi bunga salju.',
                'modal' => 3000000.00,
                'harga_jual' => 4000000.00,
                'gambar' => 'hidup.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Mobil Pengantin',
                'kategori_id' => 6,
                'deskripsi' => 'Mobil pengantin dengan dekorasi bunga.',
                'modal' => 500000.00,
                'harga_jual' => 800000.00,
                'gambar' => 'mobil.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Shooting foto',
                'kategori_id' => 5,
                'deskripsi' => 'Dokumentasi foto dan video ( 3 jam, 3 roll).',
                'modal' => 800000.00,
                'harga_jual' => 1350000.00,
                'gambar' => 'dok.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_paket' => 'Photo Booth',
                'kategori_id' => 5,
                'deskripsi' => 'Photo booth untuk acara.',
                'modal' => 900000.00,
                'harga_jual' => 1500000.00,
                'gambar' => 'booth.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}